/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SearchResultsRouteImport } from './routes/search-results'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingReadyRouteImport } from './routes/onboarding-ready'
import { Route as OnboardingPrivacyRouteImport } from './routes/onboarding-privacy'
import { Route as OnboardingPermissionsRouteImport } from './routes/onboarding-permissions'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MonthlyWrapRouteImport } from './routes/monthly-wrap'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CaptureReceiptRouteImport } from './routes/capture-receipt'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillsIndexRouteImport } from './routes/bills.index'
import { Route as TransactionsTransferRouteImport } from './routes/transactions.transfer'
import { Route as TransactionsReconcileRouteImport } from './routes/transactions.reconcile'
import { Route as TransactionsNewRouteImport } from './routes/transactions.new'
import { Route as TransactionsCategoryRouteImport } from './routes/transactions.category'
import { Route as TransactionsBulkRouteImport } from './routes/transactions.bulk'
import { Route as TransactionsIdRouteImport } from './routes/transactions.$id'
import { Route as BudgetsTransferRouteImport } from './routes/budgets.transfer'
import { Route as BudgetsNewRouteImport } from './routes/budgets.new'
import { Route as BudgetsMethodRouteImport } from './routes/budgets.method'
import { Route as BudgetsCloseRouteImport } from './routes/budgets.close'
import { Route as BudgetsIdRouteImport } from './routes/budgets.$id'
import { Route as BillsSubscriptionsRouteImport } from './routes/bills.subscriptions'
import { Route as BillsNewRouteImport } from './routes/bills.new'
import { Route as BillsIdRouteImport } from './routes/bills.$id'
import { Route as BillsSubscriptionsIndexRouteImport } from './routes/bills.subscriptions.index'
import { Route as TransactionsIdSplitRouteImport } from './routes/transactions.$id.split'
import { Route as TransactionsIdRefundRouteImport } from './routes/transactions.$id.refund'
import { Route as TransactionsIdEditRouteImport } from './routes/transactions.$id.edit'
import { Route as BudgetsIdEditRouteImport } from './routes/budgets.$id.edit'
import { Route as BudgetsIdAlertRouteImport } from './routes/budgets.$id.alert'
import { Route as BillsSubscriptionsNewRouteImport } from './routes/bills.subscriptions.new'
import { Route as BillsIdEditRouteImport } from './routes/bills.$id.edit'
import { Route as BillsSubscriptionsIdAlertRouteImport } from './routes/bills.subscriptions.$id.alert'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchResultsRoute = SearchResultsRouteImport.update({
  id: '/search-results',
  path: '/search-results',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingReadyRoute = OnboardingReadyRouteImport.update({
  id: '/onboarding-ready',
  path: '/onboarding-ready',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPrivacyRoute = OnboardingPrivacyRouteImport.update({
  id: '/onboarding-privacy',
  path: '/onboarding-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPermissionsRoute = OnboardingPermissionsRouteImport.update({
  id: '/onboarding-permissions',
  path: '/onboarding-permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyWrapRoute = MonthlyWrapRouteImport.update({
  id: '/monthly-wrap',
  path: '/monthly-wrap',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureReceiptRoute = CaptureReceiptRouteImport.update({
  id: '/capture-receipt',
  path: '/capture-receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIndexRoute = BillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BillsRoute,
} as any)
const TransactionsTransferRoute = TransactionsTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => TransactionsRoute,
} as any)
const TransactionsReconcileRoute = TransactionsReconcileRouteImport.update({
  id: '/reconcile',
  path: '/reconcile',
  getParentRoute: () => TransactionsRoute,
} as any)
const TransactionsNewRoute = TransactionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TransactionsRoute,
} as any)
const TransactionsCategoryRoute = TransactionsCategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => TransactionsRoute,
} as any)
const TransactionsBulkRoute = TransactionsBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => TransactionsRoute,
} as any)
const TransactionsIdRoute = TransactionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TransactionsRoute,
} as any)
const BudgetsTransferRoute = BudgetsTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => BudgetsRoute,
} as any)
const BudgetsNewRoute = BudgetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BudgetsRoute,
} as any)
const BudgetsMethodRoute = BudgetsMethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => BudgetsRoute,
} as any)
const BudgetsCloseRoute = BudgetsCloseRouteImport.update({
  id: '/close',
  path: '/close',
  getParentRoute: () => BudgetsRoute,
} as any)
const BudgetsIdRoute = BudgetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BudgetsRoute,
} as any)
const BillsSubscriptionsRoute = BillsSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => BillsRoute,
} as any)
const BillsNewRoute = BillsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BillsRoute,
} as any)
const BillsIdRoute = BillsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BillsRoute,
} as any)
const BillsSubscriptionsIndexRoute = BillsSubscriptionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BillsSubscriptionsRoute,
} as any)
const TransactionsIdSplitRoute = TransactionsIdSplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => TransactionsIdRoute,
} as any)
const TransactionsIdRefundRoute = TransactionsIdRefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => TransactionsIdRoute,
} as any)
const TransactionsIdEditRoute = TransactionsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TransactionsIdRoute,
} as any)
const BudgetsIdEditRoute = BudgetsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BudgetsIdRoute,
} as any)
const BudgetsIdAlertRoute = BudgetsIdAlertRouteImport.update({
  id: '/alert',
  path: '/alert',
  getParentRoute: () => BudgetsIdRoute,
} as any)
const BillsSubscriptionsNewRoute = BillsSubscriptionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BillsSubscriptionsRoute,
} as any)
const BillsIdEditRoute = BillsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BillsIdRoute,
} as any)
const BillsSubscriptionsIdAlertRoute =
  BillsSubscriptionsIdAlertRouteImport.update({
    id: '/$id/alert',
    path: '/$id/alert',
    getParentRoute: () => BillsSubscriptionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bills': typeof BillsRouteWithChildren
  '/budgets': typeof BudgetsRouteWithChildren
  '/capture-receipt': typeof CaptureReceiptRoute
  '/categories': typeof CategoriesRoute
  '/expenses': typeof ExpensesRoute
  '/inbox': typeof InboxRoute
  '/monthly-wrap': typeof MonthlyWrapRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding-permissions': typeof OnboardingPermissionsRoute
  '/onboarding-privacy': typeof OnboardingPrivacyRoute
  '/onboarding-ready': typeof OnboardingReadyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/search-results': typeof SearchResultsRoute
  '/transactions': typeof TransactionsRouteWithChildren
  '/verify-otp': typeof VerifyOtpRoute
  '/wallets': typeof WalletsRoute
  '/welcome': typeof WelcomeRoute
  '/bills/$id': typeof BillsIdRouteWithChildren
  '/bills/new': typeof BillsNewRoute
  '/bills/subscriptions': typeof BillsSubscriptionsRouteWithChildren
  '/budgets/$id': typeof BudgetsIdRouteWithChildren
  '/budgets/close': typeof BudgetsCloseRoute
  '/budgets/method': typeof BudgetsMethodRoute
  '/budgets/new': typeof BudgetsNewRoute
  '/budgets/transfer': typeof BudgetsTransferRoute
  '/transactions/$id': typeof TransactionsIdRouteWithChildren
  '/transactions/bulk': typeof TransactionsBulkRoute
  '/transactions/category': typeof TransactionsCategoryRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/transactions/reconcile': typeof TransactionsReconcileRoute
  '/transactions/transfer': typeof TransactionsTransferRoute
  '/bills/': typeof BillsIndexRoute
  '/bills/$id/edit': typeof BillsIdEditRoute
  '/bills/subscriptions/new': typeof BillsSubscriptionsNewRoute
  '/budgets/$id/alert': typeof BudgetsIdAlertRoute
  '/budgets/$id/edit': typeof BudgetsIdEditRoute
  '/transactions/$id/edit': typeof TransactionsIdEditRoute
  '/transactions/$id/refund': typeof TransactionsIdRefundRoute
  '/transactions/$id/split': typeof TransactionsIdSplitRoute
  '/bills/subscriptions/': typeof BillsSubscriptionsIndexRoute
  '/bills/subscriptions/$id/alert': typeof BillsSubscriptionsIdAlertRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/budgets': typeof BudgetsRouteWithChildren
  '/capture-receipt': typeof CaptureReceiptRoute
  '/categories': typeof CategoriesRoute
  '/expenses': typeof ExpensesRoute
  '/inbox': typeof InboxRoute
  '/monthly-wrap': typeof MonthlyWrapRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding-permissions': typeof OnboardingPermissionsRoute
  '/onboarding-privacy': typeof OnboardingPrivacyRoute
  '/onboarding-ready': typeof OnboardingReadyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/search-results': typeof SearchResultsRoute
  '/transactions': typeof TransactionsRouteWithChildren
  '/verify-otp': typeof VerifyOtpRoute
  '/wallets': typeof WalletsRoute
  '/welcome': typeof WelcomeRoute
  '/bills/$id': typeof BillsIdRouteWithChildren
  '/bills/new': typeof BillsNewRoute
  '/budgets/$id': typeof BudgetsIdRouteWithChildren
  '/budgets/close': typeof BudgetsCloseRoute
  '/budgets/method': typeof BudgetsMethodRoute
  '/budgets/new': typeof BudgetsNewRoute
  '/budgets/transfer': typeof BudgetsTransferRoute
  '/transactions/$id': typeof TransactionsIdRouteWithChildren
  '/transactions/bulk': typeof TransactionsBulkRoute
  '/transactions/category': typeof TransactionsCategoryRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/transactions/reconcile': typeof TransactionsReconcileRoute
  '/transactions/transfer': typeof TransactionsTransferRoute
  '/bills': typeof BillsIndexRoute
  '/bills/$id/edit': typeof BillsIdEditRoute
  '/bills/subscriptions/new': typeof BillsSubscriptionsNewRoute
  '/budgets/$id/alert': typeof BudgetsIdAlertRoute
  '/budgets/$id/edit': typeof BudgetsIdEditRoute
  '/transactions/$id/edit': typeof TransactionsIdEditRoute
  '/transactions/$id/refund': typeof TransactionsIdRefundRoute
  '/transactions/$id/split': typeof TransactionsIdSplitRoute
  '/bills/subscriptions': typeof BillsSubscriptionsIndexRoute
  '/bills/subscriptions/$id/alert': typeof BillsSubscriptionsIdAlertRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bills': typeof BillsRouteWithChildren
  '/budgets': typeof BudgetsRouteWithChildren
  '/capture-receipt': typeof CaptureReceiptRoute
  '/categories': typeof CategoriesRoute
  '/expenses': typeof ExpensesRoute
  '/inbox': typeof InboxRoute
  '/monthly-wrap': typeof MonthlyWrapRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding-permissions': typeof OnboardingPermissionsRoute
  '/onboarding-privacy': typeof OnboardingPrivacyRoute
  '/onboarding-ready': typeof OnboardingReadyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/search-results': typeof SearchResultsRoute
  '/transactions': typeof TransactionsRouteWithChildren
  '/verify-otp': typeof VerifyOtpRoute
  '/wallets': typeof WalletsRoute
  '/welcome': typeof WelcomeRoute
  '/bills/$id': typeof BillsIdRouteWithChildren
  '/bills/new': typeof BillsNewRoute
  '/bills/subscriptions': typeof BillsSubscriptionsRouteWithChildren
  '/budgets/$id': typeof BudgetsIdRouteWithChildren
  '/budgets/close': typeof BudgetsCloseRoute
  '/budgets/method': typeof BudgetsMethodRoute
  '/budgets/new': typeof BudgetsNewRoute
  '/budgets/transfer': typeof BudgetsTransferRoute
  '/transactions/$id': typeof TransactionsIdRouteWithChildren
  '/transactions/bulk': typeof TransactionsBulkRoute
  '/transactions/category': typeof TransactionsCategoryRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/transactions/reconcile': typeof TransactionsReconcileRoute
  '/transactions/transfer': typeof TransactionsTransferRoute
  '/bills/': typeof BillsIndexRoute
  '/bills/$id/edit': typeof BillsIdEditRoute
  '/bills/subscriptions/new': typeof BillsSubscriptionsNewRoute
  '/budgets/$id/alert': typeof BudgetsIdAlertRoute
  '/budgets/$id/edit': typeof BudgetsIdEditRoute
  '/transactions/$id/edit': typeof TransactionsIdEditRoute
  '/transactions/$id/refund': typeof TransactionsIdRefundRoute
  '/transactions/$id/split': typeof TransactionsIdSplitRoute
  '/bills/subscriptions/': typeof BillsSubscriptionsIndexRoute
  '/bills/subscriptions/$id/alert': typeof BillsSubscriptionsIdAlertRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bills'
    | '/budgets'
    | '/capture-receipt'
    | '/categories'
    | '/expenses'
    | '/inbox'
    | '/monthly-wrap'
    | '/notifications'
    | '/onboarding-permissions'
    | '/onboarding-privacy'
    | '/onboarding-ready'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/search-results'
    | '/transactions'
    | '/verify-otp'
    | '/wallets'
    | '/welcome'
    | '/bills/$id'
    | '/bills/new'
    | '/bills/subscriptions'
    | '/budgets/$id'
    | '/budgets/close'
    | '/budgets/method'
    | '/budgets/new'
    | '/budgets/transfer'
    | '/transactions/$id'
    | '/transactions/bulk'
    | '/transactions/category'
    | '/transactions/new'
    | '/transactions/reconcile'
    | '/transactions/transfer'
    | '/bills/'
    | '/bills/$id/edit'
    | '/bills/subscriptions/new'
    | '/budgets/$id/alert'
    | '/budgets/$id/edit'
    | '/transactions/$id/edit'
    | '/transactions/$id/refund'
    | '/transactions/$id/split'
    | '/bills/subscriptions/'
    | '/bills/subscriptions/$id/alert'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/budgets'
    | '/capture-receipt'
    | '/categories'
    | '/expenses'
    | '/inbox'
    | '/monthly-wrap'
    | '/notifications'
    | '/onboarding-permissions'
    | '/onboarding-privacy'
    | '/onboarding-ready'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/search-results'
    | '/transactions'
    | '/verify-otp'
    | '/wallets'
    | '/welcome'
    | '/bills/$id'
    | '/bills/new'
    | '/budgets/$id'
    | '/budgets/close'
    | '/budgets/method'
    | '/budgets/new'
    | '/budgets/transfer'
    | '/transactions/$id'
    | '/transactions/bulk'
    | '/transactions/category'
    | '/transactions/new'
    | '/transactions/reconcile'
    | '/transactions/transfer'
    | '/bills'
    | '/bills/$id/edit'
    | '/bills/subscriptions/new'
    | '/budgets/$id/alert'
    | '/budgets/$id/edit'
    | '/transactions/$id/edit'
    | '/transactions/$id/refund'
    | '/transactions/$id/split'
    | '/bills/subscriptions'
    | '/bills/subscriptions/$id/alert'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bills'
    | '/budgets'
    | '/capture-receipt'
    | '/categories'
    | '/expenses'
    | '/inbox'
    | '/monthly-wrap'
    | '/notifications'
    | '/onboarding-permissions'
    | '/onboarding-privacy'
    | '/onboarding-ready'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/search-results'
    | '/transactions'
    | '/verify-otp'
    | '/wallets'
    | '/welcome'
    | '/bills/$id'
    | '/bills/new'
    | '/bills/subscriptions'
    | '/budgets/$id'
    | '/budgets/close'
    | '/budgets/method'
    | '/budgets/new'
    | '/budgets/transfer'
    | '/transactions/$id'
    | '/transactions/bulk'
    | '/transactions/category'
    | '/transactions/new'
    | '/transactions/reconcile'
    | '/transactions/transfer'
    | '/bills/'
    | '/bills/$id/edit'
    | '/bills/subscriptions/new'
    | '/budgets/$id/alert'
    | '/budgets/$id/edit'
    | '/transactions/$id/edit'
    | '/transactions/$id/refund'
    | '/transactions/$id/split'
    | '/bills/subscriptions/'
    | '/bills/subscriptions/$id/alert'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BillsRoute: typeof BillsRouteWithChildren
  BudgetsRoute: typeof BudgetsRouteWithChildren
  CaptureReceiptRoute: typeof CaptureReceiptRoute
  CategoriesRoute: typeof CategoriesRoute
  ExpensesRoute: typeof ExpensesRoute
  InboxRoute: typeof InboxRoute
  MonthlyWrapRoute: typeof MonthlyWrapRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingPermissionsRoute: typeof OnboardingPermissionsRoute
  OnboardingPrivacyRoute: typeof OnboardingPrivacyRoute
  OnboardingReadyRoute: typeof OnboardingReadyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SearchResultsRoute: typeof SearchResultsRoute
  TransactionsRoute: typeof TransactionsRouteWithChildren
  VerifyOtpRoute: typeof VerifyOtpRoute
  WalletsRoute: typeof WalletsRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-results': {
      id: '/search-results'
      path: '/search-results'
      fullPath: '/search-results'
      preLoaderRoute: typeof SearchResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-ready': {
      id: '/onboarding-ready'
      path: '/onboarding-ready'
      fullPath: '/onboarding-ready'
      preLoaderRoute: typeof OnboardingReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-privacy': {
      id: '/onboarding-privacy'
      path: '/onboarding-privacy'
      fullPath: '/onboarding-privacy'
      preLoaderRoute: typeof OnboardingPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-permissions': {
      id: '/onboarding-permissions'
      path: '/onboarding-permissions'
      fullPath: '/onboarding-permissions'
      preLoaderRoute: typeof OnboardingPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly-wrap': {
      id: '/monthly-wrap'
      path: '/monthly-wrap'
      fullPath: '/monthly-wrap'
      preLoaderRoute: typeof MonthlyWrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture-receipt': {
      id: '/capture-receipt'
      path: '/capture-receipt'
      fullPath: '/capture-receipt'
      preLoaderRoute: typeof CaptureReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/': {
      id: '/bills/'
      path: '/'
      fullPath: '/bills/'
      preLoaderRoute: typeof BillsIndexRouteImport
      parentRoute: typeof BillsRoute
    }
    '/transactions/transfer': {
      id: '/transactions/transfer'
      path: '/transfer'
      fullPath: '/transactions/transfer'
      preLoaderRoute: typeof TransactionsTransferRouteImport
      parentRoute: typeof TransactionsRoute
    }
    '/transactions/reconcile': {
      id: '/transactions/reconcile'
      path: '/reconcile'
      fullPath: '/transactions/reconcile'
      preLoaderRoute: typeof TransactionsReconcileRouteImport
      parentRoute: typeof TransactionsRoute
    }
    '/transactions/new': {
      id: '/transactions/new'
      path: '/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof TransactionsNewRouteImport
      parentRoute: typeof TransactionsRoute
    }
    '/transactions/category': {
      id: '/transactions/category'
      path: '/category'
      fullPath: '/transactions/category'
      preLoaderRoute: typeof TransactionsCategoryRouteImport
      parentRoute: typeof TransactionsRoute
    }
    '/transactions/bulk': {
      id: '/transactions/bulk'
      path: '/bulk'
      fullPath: '/transactions/bulk'
      preLoaderRoute: typeof TransactionsBulkRouteImport
      parentRoute: typeof TransactionsRoute
    }
    '/transactions/$id': {
      id: '/transactions/$id'
      path: '/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof TransactionsIdRouteImport
      parentRoute: typeof TransactionsRoute
    }
    '/budgets/transfer': {
      id: '/budgets/transfer'
      path: '/transfer'
      fullPath: '/budgets/transfer'
      preLoaderRoute: typeof BudgetsTransferRouteImport
      parentRoute: typeof BudgetsRoute
    }
    '/budgets/new': {
      id: '/budgets/new'
      path: '/new'
      fullPath: '/budgets/new'
      preLoaderRoute: typeof BudgetsNewRouteImport
      parentRoute: typeof BudgetsRoute
    }
    '/budgets/method': {
      id: '/budgets/method'
      path: '/method'
      fullPath: '/budgets/method'
      preLoaderRoute: typeof BudgetsMethodRouteImport
      parentRoute: typeof BudgetsRoute
    }
    '/budgets/close': {
      id: '/budgets/close'
      path: '/close'
      fullPath: '/budgets/close'
      preLoaderRoute: typeof BudgetsCloseRouteImport
      parentRoute: typeof BudgetsRoute
    }
    '/budgets/$id': {
      id: '/budgets/$id'
      path: '/$id'
      fullPath: '/budgets/$id'
      preLoaderRoute: typeof BudgetsIdRouteImport
      parentRoute: typeof BudgetsRoute
    }
    '/bills/subscriptions': {
      id: '/bills/subscriptions'
      path: '/subscriptions'
      fullPath: '/bills/subscriptions'
      preLoaderRoute: typeof BillsSubscriptionsRouteImport
      parentRoute: typeof BillsRoute
    }
    '/bills/new': {
      id: '/bills/new'
      path: '/new'
      fullPath: '/bills/new'
      preLoaderRoute: typeof BillsNewRouteImport
      parentRoute: typeof BillsRoute
    }
    '/bills/$id': {
      id: '/bills/$id'
      path: '/$id'
      fullPath: '/bills/$id'
      preLoaderRoute: typeof BillsIdRouteImport
      parentRoute: typeof BillsRoute
    }
    '/bills/subscriptions/': {
      id: '/bills/subscriptions/'
      path: '/'
      fullPath: '/bills/subscriptions/'
      preLoaderRoute: typeof BillsSubscriptionsIndexRouteImport
      parentRoute: typeof BillsSubscriptionsRoute
    }
    '/transactions/$id/split': {
      id: '/transactions/$id/split'
      path: '/split'
      fullPath: '/transactions/$id/split'
      preLoaderRoute: typeof TransactionsIdSplitRouteImport
      parentRoute: typeof TransactionsIdRoute
    }
    '/transactions/$id/refund': {
      id: '/transactions/$id/refund'
      path: '/refund'
      fullPath: '/transactions/$id/refund'
      preLoaderRoute: typeof TransactionsIdRefundRouteImport
      parentRoute: typeof TransactionsIdRoute
    }
    '/transactions/$id/edit': {
      id: '/transactions/$id/edit'
      path: '/edit'
      fullPath: '/transactions/$id/edit'
      preLoaderRoute: typeof TransactionsIdEditRouteImport
      parentRoute: typeof TransactionsIdRoute
    }
    '/budgets/$id/edit': {
      id: '/budgets/$id/edit'
      path: '/edit'
      fullPath: '/budgets/$id/edit'
      preLoaderRoute: typeof BudgetsIdEditRouteImport
      parentRoute: typeof BudgetsIdRoute
    }
    '/budgets/$id/alert': {
      id: '/budgets/$id/alert'
      path: '/alert'
      fullPath: '/budgets/$id/alert'
      preLoaderRoute: typeof BudgetsIdAlertRouteImport
      parentRoute: typeof BudgetsIdRoute
    }
    '/bills/subscriptions/new': {
      id: '/bills/subscriptions/new'
      path: '/new'
      fullPath: '/bills/subscriptions/new'
      preLoaderRoute: typeof BillsSubscriptionsNewRouteImport
      parentRoute: typeof BillsSubscriptionsRoute
    }
    '/bills/$id/edit': {
      id: '/bills/$id/edit'
      path: '/edit'
      fullPath: '/bills/$id/edit'
      preLoaderRoute: typeof BillsIdEditRouteImport
      parentRoute: typeof BillsIdRoute
    }
    '/bills/subscriptions/$id/alert': {
      id: '/bills/subscriptions/$id/alert'
      path: '/$id/alert'
      fullPath: '/bills/subscriptions/$id/alert'
      preLoaderRoute: typeof BillsSubscriptionsIdAlertRouteImport
      parentRoute: typeof BillsSubscriptionsRoute
    }
  }
}

interface BillsIdRouteChildren {
  BillsIdEditRoute: typeof BillsIdEditRoute
}

const BillsIdRouteChildren: BillsIdRouteChildren = {
  BillsIdEditRoute: BillsIdEditRoute,
}

const BillsIdRouteWithChildren =
  BillsIdRoute._addFileChildren(BillsIdRouteChildren)

interface BillsSubscriptionsRouteChildren {
  BillsSubscriptionsNewRoute: typeof BillsSubscriptionsNewRoute
  BillsSubscriptionsIndexRoute: typeof BillsSubscriptionsIndexRoute
  BillsSubscriptionsIdAlertRoute: typeof BillsSubscriptionsIdAlertRoute
}

const BillsSubscriptionsRouteChildren: BillsSubscriptionsRouteChildren = {
  BillsSubscriptionsNewRoute: BillsSubscriptionsNewRoute,
  BillsSubscriptionsIndexRoute: BillsSubscriptionsIndexRoute,
  BillsSubscriptionsIdAlertRoute: BillsSubscriptionsIdAlertRoute,
}

const BillsSubscriptionsRouteWithChildren =
  BillsSubscriptionsRoute._addFileChildren(BillsSubscriptionsRouteChildren)

interface BillsRouteChildren {
  BillsIdRoute: typeof BillsIdRouteWithChildren
  BillsNewRoute: typeof BillsNewRoute
  BillsSubscriptionsRoute: typeof BillsSubscriptionsRouteWithChildren
  BillsIndexRoute: typeof BillsIndexRoute
}

const BillsRouteChildren: BillsRouteChildren = {
  BillsIdRoute: BillsIdRouteWithChildren,
  BillsNewRoute: BillsNewRoute,
  BillsSubscriptionsRoute: BillsSubscriptionsRouteWithChildren,
  BillsIndexRoute: BillsIndexRoute,
}

const BillsRouteWithChildren = BillsRoute._addFileChildren(BillsRouteChildren)

interface BudgetsIdRouteChildren {
  BudgetsIdAlertRoute: typeof BudgetsIdAlertRoute
  BudgetsIdEditRoute: typeof BudgetsIdEditRoute
}

const BudgetsIdRouteChildren: BudgetsIdRouteChildren = {
  BudgetsIdAlertRoute: BudgetsIdAlertRoute,
  BudgetsIdEditRoute: BudgetsIdEditRoute,
}

const BudgetsIdRouteWithChildren = BudgetsIdRoute._addFileChildren(
  BudgetsIdRouteChildren,
)

interface BudgetsRouteChildren {
  BudgetsIdRoute: typeof BudgetsIdRouteWithChildren
  BudgetsCloseRoute: typeof BudgetsCloseRoute
  BudgetsMethodRoute: typeof BudgetsMethodRoute
  BudgetsNewRoute: typeof BudgetsNewRoute
  BudgetsTransferRoute: typeof BudgetsTransferRoute
}

const BudgetsRouteChildren: BudgetsRouteChildren = {
  BudgetsIdRoute: BudgetsIdRouteWithChildren,
  BudgetsCloseRoute: BudgetsCloseRoute,
  BudgetsMethodRoute: BudgetsMethodRoute,
  BudgetsNewRoute: BudgetsNewRoute,
  BudgetsTransferRoute: BudgetsTransferRoute,
}

const BudgetsRouteWithChildren =
  BudgetsRoute._addFileChildren(BudgetsRouteChildren)

interface TransactionsIdRouteChildren {
  TransactionsIdEditRoute: typeof TransactionsIdEditRoute
  TransactionsIdRefundRoute: typeof TransactionsIdRefundRoute
  TransactionsIdSplitRoute: typeof TransactionsIdSplitRoute
}

const TransactionsIdRouteChildren: TransactionsIdRouteChildren = {
  TransactionsIdEditRoute: TransactionsIdEditRoute,
  TransactionsIdRefundRoute: TransactionsIdRefundRoute,
  TransactionsIdSplitRoute: TransactionsIdSplitRoute,
}

const TransactionsIdRouteWithChildren = TransactionsIdRoute._addFileChildren(
  TransactionsIdRouteChildren,
)

interface TransactionsRouteChildren {
  TransactionsIdRoute: typeof TransactionsIdRouteWithChildren
  TransactionsBulkRoute: typeof TransactionsBulkRoute
  TransactionsCategoryRoute: typeof TransactionsCategoryRoute
  TransactionsNewRoute: typeof TransactionsNewRoute
  TransactionsReconcileRoute: typeof TransactionsReconcileRoute
  TransactionsTransferRoute: typeof TransactionsTransferRoute
}

const TransactionsRouteChildren: TransactionsRouteChildren = {
  TransactionsIdRoute: TransactionsIdRouteWithChildren,
  TransactionsBulkRoute: TransactionsBulkRoute,
  TransactionsCategoryRoute: TransactionsCategoryRoute,
  TransactionsNewRoute: TransactionsNewRoute,
  TransactionsReconcileRoute: TransactionsReconcileRoute,
  TransactionsTransferRoute: TransactionsTransferRoute,
}

const TransactionsRouteWithChildren = TransactionsRoute._addFileChildren(
  TransactionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BillsRoute: BillsRouteWithChildren,
  BudgetsRoute: BudgetsRouteWithChildren,
  CaptureReceiptRoute: CaptureReceiptRoute,
  CategoriesRoute: CategoriesRoute,
  ExpensesRoute: ExpensesRoute,
  InboxRoute: InboxRoute,
  MonthlyWrapRoute: MonthlyWrapRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingPermissionsRoute: OnboardingPermissionsRoute,
  OnboardingPrivacyRoute: OnboardingPrivacyRoute,
  OnboardingReadyRoute: OnboardingReadyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SearchResultsRoute: SearchResultsRoute,
  TransactionsRoute: TransactionsRouteWithChildren,
  VerifyOtpRoute: VerifyOtpRoute,
  WalletsRoute: WalletsRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
